TestBuilder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tests/', include('tests.urls')),
    path('suchen/', include('suchen.urls')),
    path('aufgaben/', include('aufgaben.urls')),
    path('tools/', include('tools.urls')),
]

aufgaben/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:themenbereich>', views.view_aufgaben, name='aufgaben'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='Home'),
]

suchen/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.suchen, name='test_suchen'),
    path('nicht-gefunden/', views.not_found, name='nicht_gefunden'),
    path('delete/<str:name>/', views.delete, name='delete'),
]

tools/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='berechnen'),
    ]

aufgaben/models.py
from django.db import models


# Create your models here.
class Themen(models.Model):
    name = models.CharField(max_length=100)
    stufe = models.CharField(choices=[('Primärstufe', 'Primärstufe'), ('Mittelstufe', 'Mittelstufe'), ('Oberstufe', 'Oberstufe')],
                             max_length=100)
    fach = models.CharField(max_length=100, default='Mathematik')

    def __str__(self):
        return self.name

tools/models.py
from django.db import models

# Create your models here.

suchen/forms.py
from django import forms


class Suchen(forms.Form):
    uuid_0 = forms.CharField(max_length=1, required=True)
    uuid_1 = forms.CharField(max_length=1, required=True)
    uuid_2 = forms.CharField(max_length=1, required=True)
    uuid_3 = forms.CharField(max_length=1, required=True)
    uuid_4 = forms.CharField(max_length=1, required=True)
    uuid_5 = forms.CharField(max_length=1, required=True)
    uuid_6 = forms.CharField(max_length=1, required=True)
    uuid_7 = forms.CharField(max_length=1, required=True)

aufgaben/views.py
import json

from django.shortcuts import render, redirect

from funktionen import get_aufgaben
from aufgaben.models import Themen


def view_aufgaben(request, themenbereich):
    stufe = Themen.objects.get(name=themenbereich).stufe
    temp = get_aufgaben(themenbereich)
    aufgaben = []
    params = []
    for aufgabe in temp:
        temp_params = []
        aufgaben.append(aufgabe[2:])
        split_params = str(aufgabe[-2][1]).split(' ')
        for param in split_params:
            if param != 'None':
                if param.split('=')[1].startswith('['):
                    temp_list = param.split('=')[1][1:-1].split(',')
                    param = [param.split('=')[0], 'selection', temp_list]
            else:
                param = None
            if type(param) == list or param is None:
                temp_params.append(param)
            else:
                temp_params.append(param.split('='))

        params.append(temp_params)

    if request.method == 'POST':
        form_data = request.POST.dict()
        del form_data['csrfmiddlewaretoken']
        temp_form_data = form_data.copy()

        for key, value in temp_form_data.items():
            if value == '' or value == 'Keine Vorschrift':
                form_data.pop(key)

        aufgaben = []
        for key in form_data.keys():
            if key.startswith('Aufgabe'):
                aufgaben.append(key.lstrip('Aufgabe'))

        temp_form_data = form_data.copy()
        for key in temp_form_data.keys():
            temp = []
            for aufgabe in aufgaben:
                if key.endswith(aufgabe):
                    temp.append(True)
                else:
                    temp.append(False)
            if not any(temp):
                form_data.pop(key)

        return_data = {}
        for key, value in form_data.items():
            temp_key = key.split(' ')
            return_key = '_'.join(temp_key)
            if key.startswith('BE'):
                return_value = '-'.join(value.replace(' ', '').split(','))
            else:
                temp_value = value.split(' ')
                try:
                    temp_value = int(temp_value[0])
                except ValueError:
                    pass
                if isinstance(temp_value, int):
                    return_value = temp_value
                else:
                    temp_value = str(temp_value[0])
                    if not temp_value[-1].split('_')[1:]:
                        return_value = temp_value
                    else:
                        return_value = '_'.join([temp_value, '_'.join(temp_value[-1].split('_')[1:])])

            return_data[return_key] = return_value

        json_data = json.dumps(return_data)
        print('JSON output', json_data)

        return redirect(to=f'/tests/erstellen/{themenbereich}/{json_data}')

    return render(request, 'aufgaben.html', {'aufgaben': aufgaben, 'themenbereich': themenbereich, 'stufe': stufe, 'parameter': params})

home/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html', {})

suchen/views.py
import glob
import os
import time

from django.db.models import QuerySet
from django.shortcuts import render, redirect

from tests.models import Erstellt
from suchen.forms import Suchen

path = '/'.join(os.path.abspath(__file__).split('\\')[:-2])


# Create your views here.
def suchen(request):
    if request.method == 'POST':
        form = Suchen(request.POST)
        if form.is_valid():
            uuid = ''
            for value in form.cleaned_data.values():
                uuid += str(value).upper()
                uuid += '-' if len(uuid) == 4 else ''

            test_db: QuerySet = Erstellt.objects.filter(uuid=uuid).values()
            if test_db:
                test_db_str = f'{test_db[0]['identifier']} {test_db[0]['uuid']}'
            else:
                test_db_str = None

            test_file = glob.glob(f'{path}/skripteTests/pdf/*{uuid}.pdf')
            test_file_str = test_file[0].split('\\')[1][:-4] if test_file else None

            if test_db_str == test_file_str and (
                    test_db_str is not None and test_db_str is not None):
                return redirect(to=f'/tests/{test_db_str}/')
            else:
                return redirect(to=f'nicht-gefunden/')
    else:
        form = Suchen()
    return render(request, 'suchen.html', {'form': form})


def not_found(request):
    return render(request, 'nichtGefunden.html')


def delete(request, name):
    Erstellt.objects.filter(uuid=name.split(' ')[-1]).delete()
    os.remove(f'{path}/skripteTests/pdf/{name}.pdf')
    os.remove(f'{path}/skripteTests/pdf/{name} - Lsg.pdf')
    time.sleep(1)
    return redirect(to=f'/')

tools/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'tools.html')

aufgaben/templates/aufgaben.html
{% extends 'base.html' %}
{% load clean_auswahl %}
{% load index %}
{% load multi_bsp %}
{% block title %}
    {{ themenbereich }}
{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'aufgaben/style.css' %}"/>
{% endblock %}
{% block content %}
    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const listParent = document.querySelectorAll('.list-parent');
            const listChild = document.querySelectorAll('.list-child');

            const checkboxGroups = document.querySelectorAll('.checkbox-group');

            checkboxGroups.forEach(group => {
                const parentCheckbox = group.querySelector('.parentCheckbox');
                const childCheckboxes = group.querySelectorAll('.childCheckbox');

                // Funktion zum Aktualisieren des Status der Child-Checkboxen
                const updateChildCheckboxes = () => {
                    childCheckboxes.forEach(checkbox => {
                        checkbox.checked = parentCheckbox.checked;
                    });
                };

                // Funktion zum Aktualisieren des Status der Parent-Checkbox
                const updateParentCheckbox = () => {
                    if (childCheckboxes.length === 0) {
                        parentCheckbox.indeterminate = false;
                        parentCheckbox.checked = false;
                        return;
                    }

                    const allChecked = Array.from(childCheckboxes).every(checkbox => checkbox.checked);
                    const someChecked = Array.from(childCheckboxes).some(checkbox => checkbox.checked);
                    parentCheckbox.checked = allChecked;
                    parentCheckbox.indeterminate = !allChecked && someChecked;
                };

                // Event-Listener für die Parent-Checkbox
                parentCheckbox.addEventListener('change', updateChildCheckboxes);

                // Event-Listener für die Child-Checkboxen
                childCheckboxes.forEach(checkbox => {
                    checkbox.addEventListener('change', updateParentCheckbox);
                });

                // Initialer Status der Parent-Checkbox festlegen
                updateParentCheckbox();
                });

        });
    </script>

    <div class="aufgabe-div">
        <div class="aufgabe-title">
            <span class="aufgabe-subtitle rubik-200">{{ stufe }}</span>
            <h1>{{ themenbereich }}</h1>
            <span class="rubik-200">Alle Optionen für Angaben sind optional.<br>Wenn Sie nichts spezifizieren oder die Eingabe das falsche Format hat, wird ein Standardwert verwendet.</span>
        </div>
        <form method="post">
            {% csrf_token %}
            <ul class="list-group list-parent">
                {% for aufgabe in aufgaben %}
                    <li class="aufgabe list-group-item checkbox-group">
                    <div class="parent-div">
                        <div class="parent-title">
                            <input class="form-check-input me-1 parent parentCheckbox" type="checkbox" value="Aufgabe_{{forloop.counter}}"
                               id="Aufgabe_{{forloop.counter}}"
                               name="Aufgabe_{{forloop.counter}}">
                            <label class="form-check-label parent"
                               for="Aufgabe_{{forloop.counter}}">
                              {{ aufgabe.0 }}
                            </label>
                        </div>
                        {% if parameter|index:forloop.counter0 is not None %}
                            <div class="row auswahl">
                                {% for auswahl in parameter|index:forloop.counter0 %}
                                        <div class="col-md eingaben">
                                            <div class="form-floating mb-3">
                                                {% if auswahl.1 == 'selection' %}
                                                    <select name="{{ auswahl.0|clean_auswahl }}_{{ forloop.parentloop.counter }}" class="form-select" id="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}">
                                                        {% for item in auswahl.2 %}
                                                            <option value="{{ item|clean_auswahl }}">{{ item|clean_auswahl }}</option>
                                                        {% endfor %}
                                                    </select>
                                                    <label for="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}">{{ auswahl.0|clean_auswahl }}</label>
                                                {% else %}
                                                    {% if aufgabe.2|length == 0 %}
                                                        {% if auswahl.0|clean_auswahl == 'BE' %}
                                                            <input type="{{ auswahl.1 }}" name="{{ auswahl.0|clean_auswahl }}_{{ forloop.parentloop.counter }}" class="form-control" id="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}" placeholder="{{ auswahl.0|clean_auswahl }}">
                                                            <label for="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}">{{ auswahl.0|clean_auswahl }} &nbsp;<span class="rubik-200 eingabe-bsp">Bsp: {{ aufgabe.2|length|multi_bsp }}</span></label>
                                                        {% else %}
                                                            <input type="{{ auswahl.1 }}" name="{{ auswahl.0|clean_auswahl }}_{{ forloop.parentloop.counter }}" class="form-control" id="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}" placeholder="{{ auswahl.0|clean_auswahl }}">
                                                            <label for="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}">{{ auswahl.0|clean_auswahl }}</label>
                                                        {% endif %}
                                                    {% else %}
                                                        <input type="{{ auswahl.1 }}" name="{{ auswahl.0|clean_auswahl }}_{{ forloop.parentloop.counter }}" class="form-control" id="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}" placeholder="{{ auswahl.0|clean_auswahl }}">
                                                        <label for="floating_{{ auswahl.0 }}_{{ forloop.parentloop.counter }}">{{ auswahl.0|clean_auswahl }} &nbsp;<span class="rubik-200 eingabe-bsp">Bsp: {{ aufgabe.2|length|multi_bsp }}</span></label>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        </div>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                        {% if aufgabe.2 %}
                            <ul class="list-group list-child" style="margin-top: 2%;">
                                {% for teilaufg in aufgabe.2 %}
                                    <li class="list-group-item">
                                        <div class="form-check child-div">
                                            <input class="form-check-input me-1 childCheckbox" type="checkbox" value="Aufgabe_{{forloop.parentloop.counter}}_{{forloop.counter}}"
                                                   id="Aufgabe_{{forloop.parentloop.counter}}_{{forloop.counter}}"
                                                   name="Aufgabe_{{forloop.parentloop.counter}}_{{forloop.counter}}">
                                            <label class="form-check-label child-label"
                                                   for="Aufgabe_{{forloop.parentloop.counter}}_{{forloop.counter}}">
                                                {{ teilaufg.1 }}
                                            </label>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" class="btn-weiter btn btn-outline-secondary" value="Weiter">
        </form>
    </div>
{% endblock %}

home/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
{% endblock %}
{% block content %}
    <div class="home-wrapper">
        <div class="home-title libre-bodoni-400">
            <p>
            Test<br>Builder
            </p>
        </div>
        <div class="home-subtitle poppins-300">
            <p>
                Automatisierte Erstellung von Tests mithilfe von Python und LaTeX zur Leistungsabfrage von Schülerinnen und Schülern
                <br><br>
                Der Code des <a href="https://github.com/HerrjeAlf/TestBuilder" target="_blank"
                   class="link-secondary link-underline-opacity-25">TestBuilders</a> und der <a href="https://github.com/nickolas07/TestBuilder-website" target="_blank"
                   class="link-secondary link-underline-opacity-25">Website</a> ist auf GitHub verfügbar
            </p>
        </div>
    </div>
{% endblock %}

suchen/templates/nichtGefunden.html
{% extends 'base.html' %}
{% block title %}Nicht Gefunden{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'suchen/style.css' %}"/>
{% endblock %}
{% block content %}
    <div class="nicht-gefunden">
        <span class="bb2d3b">Keinen Test gefunden</span>
        <br>
        <a type="button" href="/suchen" class="btn btn-outline-secondary btn-zurück link-light link-offset-2 link-underline link-underline-opacity-0">Zurück</a>
    </div>
{% endblock %}

suchen/templates/suchen.html
{% extends 'base.html' %}
{% block title %}Suchen{% endblock %}
{% load static %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'suchen/style.css' %}"/>
{% endblock %}
{% block content %}
<script>
document.addEventListener("DOMContentLoaded", function() {
    const codeForm = document.getElementById('codeForm');
    const codeInputs = Array.from(document.querySelectorAll('.code'));
    const submitBtn = document.getElementById('submit-btn');
    const submitText = document.getElementById('submit-text');
    const spinner = submitBtn.querySelector('.spinner-border');

    spinner.hidden = true;

    codeInputs.forEach((input, index) => {
        input.addEventListener('keydown', (e) => {
            if (e.key === 'Backspace' && index !== 0 && !input.value) {
                codeInputs[index - 1].focus();
            }
        });

        input.addEventListener('input', ({ data, inputType }) => {
            if (inputType !== "deleteContentBackward") {
                if (data) {
                    const alphanumeric = data.toUpperCase().match(/[0-9A-Z]/);
                    input.value = alphanumeric ? alphanumeric[0] : "";

                    if (input.value && index !== codeInputs.length - 1) {
                        codeInputs[index + 1].focus();
                    }
                }
            }
        })
    });

    document.body.addEventListener('paste', (e) => {
        if (document.activeElement.classList.contains('code')) {
            let paste = (e.clipboardData || window.clipboardData).getData('text');
            paste = paste.toUpperCase().replace(/[^0-9A-Z-]/g, '');

            if (paste.length === 9 && paste[4] === '-') {
                codeInputs.forEach((input, i) => {
                    input.value = paste[i >= 4 ? i + 1 : i];
                });
                codeInputs.forEach(input => input.readOnly = true);
                spinner.hidden = false;
                document.activeElement.blur();
                submitText.textContent = ''
                setTimeout(() => {
                    document.activeElement.blur();
                    codeForm.submit();
                    codeInputs.forEach(input => {
                        input.readOnly = false;
                        input.value = '';
                    });
                    spinner.hidden = true;
                }, 1000);
            }
        }
    });

    codeForm.addEventListener('submit', function(e) {
        e.preventDefault();
        codeInputs.forEach(input => input.readOnly = true);
        spinner.hidden = false;
        submitText.textContent = ''
        setTimeout(() => {
            document.activeElement.blur();
            codeForm.submit();
            codeInputs.forEach(input => {
                input.readOnly = false;
                input.value = '';
            });
            spinner.hidden = true;
        }, 1000);
    });
});
</script>
<div class="test-suchen">
    <div class="title-suchen libre-bodoni-400">
        Test suchen
    </div>
    <form method="post" id="codeForm" class="code-wrapper">
        {% csrf_token %}
        <div class="code-group ibm-plex-mono-400" id="codeGroup">
            <input id="id_uuid_0" name="uuid_0" class="code form-control form-control-lg me-3" type="text" maxlength="1" autocomplete="off" required autofocus/>
            <input id="id_uuid_1" name="uuid_1" class="code form-control form-control-lg me-3" type="text" maxlength="1" autocomplete="off" required/>
            <input id="id_uuid_2" name="uuid_2" class="code form-control form-control-lg me-3" type="text" maxlength="1" autocomplete="off" required/>
            <input id="id_uuid_3" name="uuid_3" class="code form-control form-control-lg me-3" type="text" maxlength="1" autocomplete="off" required/>
            <span style="font-size: 5vw; grid-column: span 4">&ndash;</span>
            <input id="id_uuid_4" name="uuid_4" class="code form-control form-control-lg ms-3" type="text" maxlength="1" autocomplete="off" required/>
            <input id="id_uuid_5" name="uuid_5" class="code form-control form-control-lg ms-3" type="text" maxlength="1" autocomplete="off" required/>
            <input id="id_uuid_6" name="uuid_6" class="code form-control form-control-lg ms-3" type="text" maxlength="1" autocomplete="off" required/>
            <input id="id_uuid_7" name="uuid_7" class="code form-control form-control-lg ms-3" type="text" maxlength="1" autocomplete="off" required/>
        </div>
        <button type="submit" id="submit-btn" class="btn btn-success">
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            <span id="submit-text">Suchen</span>
        </button>
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="de" data-bs-theme="dark">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}TestBuilder{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
        {% block head %}
        
        {% endblock %}
        <script src="{% static 'script.js' %}"></script>
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                setTheme(localStorage.getItem('theme') || 'light');
            })
        </script>
    </head>
    <body class="rubik-400">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand libre-bodoni-400" href="/">TestBuilder</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse poppins-400" id="navbarNav">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="/tests/">Tests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/suchen/">Suchen</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" role="button" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                                Aufgaben
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <div class="dropend">
                                        <a role="button" class="dropdown-item" data-bs-toggle="dropdown" aria-expanded="false">
                                            Primärstufe
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="/aufgaben/Rationale%20Zahlen">Rationale Zahlen</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <div class="dropend">
                                        <a role="button" class="dropdown-item" data-bs-toggle="dropdown" aria-expanded="false">
                                            Mittelstufe
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="/aufgaben/Funktionen">Funktionen</a></li>
                                            <li><a class="dropdown-item" href="/aufgaben/Geometrie">Geometrie</a></li>
                                        </ul>
                                    </div>
                                </li>
                                <li>
                                    <div class="dropend">
                                        <a role="button" class="dropdown-item" data-bs-toggle="dropdown" aria-expanded="false">
                                            Oberstufe
                                        </a>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="/aufgaben/Algebra">Algebra</a></li>
                                            <li><a class="dropdown-item" href="/aufgaben/Analysis">Analysis</a></li>
                                            <li><a class="dropdown-item" href="/aufgaben/Wahrscheinlichkeitsrechnung">Wahrscheinlichkeit</a></li>
                                        </ul>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/tools/">Tools</a>
                        </li>
                    </ul>
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" role="switch" id="dunkel-modus" onchange="toggleTheme()">
                        <label class="form-check-label" for="dunkel-modus">Dunkel</label>
                    </div>
                </div>
            </div>
        </nav>
        <div class="content">
            {% block content %}
                
            {% endblock %}
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>